#pragma once

/*

 TESTTILE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define Assets_TestTileBank 0
/* Start of tile array. */
extern unsigned char Assets_TestTile[] =
{
  0xFF,0xFF,0x91,0x91,0xFF,0x91,0xFF,0xFF,
  0xFF,0x89,0x89,0xFF,0xFF,0xFF,0xFF,0xFF
};

/* End of TESTTILE.H */
