#include "../../util/TypeDefs.h"
/*

 CRACKEDSTONETILE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
RomByte CrackedStoneTile[] =
{
  0x7E,0x7E,0x89,0xEF,0x89,0xEF,0x8F,0xEF,
  0xE9,0xE9,0x91,0x97,0x91,0xF7,0x7E,0x7E
};

/* End of CRACKEDSTONETILE.C */
