#pragma once
#include "util/TypeDefs.h"
/*

 PLAYERTESTSPRITE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 3

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define PlayerTestSpriteBank 0
/* Start of tile array. */
extern RomByte PlayerTestSprite[];

/* End of PLAYERTESTSPRITE.H */
