#pragma once
#include "../../util/TypeDefs.h"

/*

 TESTTILEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 255 x 16
   Tile set      : C:\Dev\turbo-trooper-game-boy-version\turbo-trooper-game-boy-version\art\tile_set.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TestTileMapWidth 255
#define TestTileMapHeight 16
#define TestTileMapBank 0

extern RomBytes TestTileMap[];

/* End of TESTTILEMAP.H */
